## 1. Creating user defined machines from the provided inventory        
- hosts: "InternalUserVMsGroup"
  tasks:
    - name: Creating user defined machines from the provided inventory
      import_tasks: create_vm_from_template.yml

## 2. Generate cfg file for the perimeter router
- hosts: perRouter
  tasks:
    - name: Generate cfg file for the perimeter router
      import_tasks: create_perimeter_config/prepare_hp_config_file.yml

## 3. Generate static ip-mac entries in the perimeter DHCP router
- import_playbook: create_perimeter_config/generate_dhcp_entries.yml

## 4. Applying the generated configuration to perimeter router
- hosts: perRouter
  tasks:
    - name:
      import_tasks: ansible_hpe_cw7/hp_install_config.yml
      vars:
        ip_address: "internal_ip_address"

# 5. Re-newing ip address from DHCP
- hosts: localhost
  tasks:
    - name: Re-newing ip address
      shell: |
        dhclient -r
        dhclient
