- hosts: jenkinsVMM
  tasks:
    - name: Clean inventory path
      file:
        state: absent
        path: "/var/lib/jenkins/infrastructure-github/inventory/"
    - name: TODO
      copy:
        src: "{{ inventory_dir }}/"
        dest: /var/lib/jenkins/infrastructure-github/inventory/
        owner: jenkins
        group: jenkins
        mode: 0777
