- name: apply it 
  comware_install_config:
    config_file='./ansible_hpe_cw7/configs/template.cfg'
    commit_changes=true
    username={{ username }}
    password={{ password }}
    hostname={{ hostvars['perRouter'][ip_address] }}
    #no_log: True
  failed_when: false
  async: 10
